import { useState } from "react";
import { money, today, useChoices, useKeuAction, useResource } from "../api";
import type { Account, Item, Product, Stock, Vendor } from "../types";
import { BookNotice, useBook } from "../components/BookSettings";
import { Button, Empty, ErrorMessage, Field, Heading, inputClass, Pager, Panel, Table } from "../components/UI";

export default function Inventory() {
  const book = useBook();
  return <><Heading title="Persediaan Stok Ready">Pembelian/produksi non-order dicatat sebagai aset. Pengambilan ke pesanan memakai biaya FIFO per batch dan masuk HPP.</Heading><BookNotice />{book.data?.aktif && <StockWorkspace />}</>;
}
function StockWorkspace() {
  const [offset, setOffset] = useState(0), stocks = useResource<Stock>("/stok", offset);
  const products = useChoices<Product>("/produk"), vendors = useChoices<Vendor>("/vendor"), accounts = useChoices<Account>("/akun"), items = useChoices<Item>("/item");
  const receive = useKeuAction(), fulfill = useKeuAction();
  const [payment, setPayment] = useState("kas"), [reference, setReference] = useState(()=>crypto.randomUUID()), [outRef, setOutRef] = useState(()=>crypto.randomUUID());
  return <><ErrorMessage error={stocks.error ?? products.error ?? vendors.error ?? accounts.error ?? items.error} /><Panel title="Pembelian / Produksi Stok Ready"><form className="grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));void receive.mutateAsync({path:"/stok/masuk",body:{...values,referensi:reference,qty:Number(values.qty)}}).then(()=>{setReference(crypto.randomUUID());form.reset();}).catch(()=>{});}}><ErrorMessage error={receive.error} /><Field label="Produk stok ready"><select name="produk_id" required className={inputClass}><option value="">Pilih produk master</option>{products.data?.filter(p=>p.aktif&&p.status==="master").map(p=><option key={p.id} value={p.id}>{p.sku} · {p.nama}</option>)}</select></Field><Field label="Asal stok"><select name="sumber" className={inputClass}><option value="pembelian">Pembelian</option><option value="produksi">Produksi non-order</option></select></Field><Field label="Tanggal penerimaan stok"><input type="date" name="tanggal" required defaultValue={today()} className={inputClass} /></Field><Field label="Kuantitas stok masuk"><input type="number" name="qty" min={1} max={10000} step={1} required className={inputClass} /></Field><Field label="Biaya total batch"><input name="biaya_total" required inputMode="decimal" pattern="[0-9]+(\.[0-9]{1,2})?" className={inputClass} /></Field><Field label="Sumber pembayaran stok"><select value={payment} onChange={event=>setPayment(event.target.value)} className={inputClass}><option value="kas">Kas / Bank</option><option value="utang">Utang Vendor</option></select></Field>{payment==="kas"?<Field label="Akun kas pembelian stok"><select name="akun_kas_id" required className={inputClass}><option value="">Pilih akun aktif</option>{accounts.data?.filter(a=>a.aktif).map(a=><option key={a.id} value={a.id}>{a.nama}</option>)}</select></Field>:<Field label="Vendor stok ready"><select name="vendor_id" required className={inputClass}><option value="">Pilih vendor aktif</option>{vendors.data?.filter(v=>v.aktif).map(v=><option key={v.id} value={v.id}>{v.nama}</option>)}</select></Field>}<Field label="Catatan stok masuk"><input name="keterangan" maxLength={2000} className={inputClass} /></Field><Button type="submit" disabled={receive.isPending}>Posting Stok Masuk</Button></form></Panel>
  <Panel title="Penuhi Pesanan dari Stok Ready"><form className="grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));void fulfill.mutateAsync({path:"/stok/keluar",body:{...values,referensi:outRef,qty:Number(values.qty)}}).then(()=>{setOutRef(crypto.randomUUID());form.reset();}).catch(()=>{});}}><ErrorMessage error={fulfill.error} /><Field label="Item pesanan dari stok"><select name="item_id" required className={inputClass}><option value="">Pilih item yang dipetakan</option>{items.data?.filter(i=>products.data?.some(p=>p.id===i.produk_id&&p.aktif&&p.status==="master")).map(i=><option key={i.id} value={i.id}>{i.nama_snapshot} · {i.sumber_ref}</option>)}</select></Field><Field label="Tanggal pemakaian stok"><input type="date" name="tanggal" required defaultValue={today()} className={inputClass} /></Field><Field label="Kuantitas pemakaian stok"><input type="number" name="qty" min={1} max={10000} step={1} required className={inputClass} /></Field><Field label="Catatan pemakaian stok"><input name="keterangan" maxLength={2000} className={inputClass} /></Field><Button type="submit" disabled={fulfill.isPending}>Posting Pengambilan FIFO</Button></form><p className="mt-3 text-sm">Alokasi stok dan vendor tidak boleh melebihi jumlah item. Pemakaian berikutnya harus dibatalkan sebelum koreksi historis yang mengubah FIFO.</p></Panel>
  <Panel title="Nilai & Batch Persediaan">{!stocks.data?.rows.length?<Empty />:<Table headers={["Produk", "Stok ready", "Nilai", "Jejak batch"]}>{stocks.data.rows.map(p=><tr key={p.id} className="border-b"><td className="px-3 py-2">{p.sku} · {p.nama}</td><td>{p.qty}</td><td>{money(p.nilai)}</td><td><details><summary>Batch FIFO</summary>{p.batch.map(b=><p key={b.id}>{b.tanggal} · {b.id} · {b.qty} unit · {money(b.nilai)}</p>)}</details></td></tr>)}</Table>}<Pager offset={offset} total={stocks.data?.total??0} onChange={setOffset} /></Panel></>;
}
