import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { keu, money, today } from "../api";
import type { FinancialReports, ReportRow } from "../types";
import { BookNotice, useBook } from "../components/BookSettings";
import { ErrorMessage, Field, Heading, inputClass, Loading, Panel, Table } from "../components/UI";

function Values({ title, rows, total }: { title: string; rows: ReportRow[]; total?: string }) {
  return <Panel title={title}><Table headers={["Akun", "Kelompok", "Nilai"]}>{rows.map((row, index) => <tr key={row.id ?? `${row.kelompok}-${index}`} className="border-b"><td className="px-3 py-2">{row.nama}</td><td>{row.kelompok.replaceAll("_", " ")}</td><td className="whitespace-nowrap">{money(row.nilai)}</td></tr>)}</Table>{total !== undefined && <p className="mt-3 font-semibold">Total {money(total)}</p>}</Panel>;
}
export default function Reports() {
  const book = useBook();
  const [start, setStart] = useState(today().slice(0, 7)+"-01"), [end, setEnd] = useState(today());
  const [tab, setTab] = useState("laba_rugi");
  const valid = !!start && !!end && start <= end;
  const report = useQuery({ queryKey: ["keu", "laporan-keuangan", start, end], queryFn: () => keu<FinancialReports>(`/laporan-keuangan?tanggal_awal=${start}&tanggal_akhir=${end}`), enabled: !!book.data?.aktif && valid });
  const value = report.data;
  return <><Heading title="Laporan Keuangan">Laporan dari jurnal debet–kredit terposting. Jurnal batal dikecualikan; neraca disajikan per tanggal akhir dengan saldo sebelum rentang tetap dibawa.</Heading><BookNotice /><div className="mb-4 grid gap-3 sm:grid-cols-2"><Field label="Tanggal awal laporan"><input type="date" value={start} onChange={event => setStart(event.target.value)} className={inputClass} /></Field><Field label="Tanggal akhir laporan"><input type="date" value={end} onChange={event => setEnd(event.target.value)} className={inputClass} /></Field></div>{!valid && <p role="alert">Isi rentang tanggal yang valid; tanggal awal tidak boleh melebihi tanggal akhir.</p>}<ErrorMessage error={report.error} /><div role="tablist" aria-label="Laporan keuangan" className="mb-4 flex flex-wrap gap-2">{[["laba_rugi", "Laporan Laba Rugi"], ["neraca", "Laporan Posisi Keuangan"], ["arus_kas", "Laporan Arus Kas"]].map(([key, name]) => <button key={key} role="tab" aria-selected={tab === key} className={inputClass} onClick={() => setTab(key)}>{name}</button>)}</div>{report.isLoading && <Loading />}
    {book.data?.aktif && valid && value && <div role="tabpanel">{tab === "laba_rugi" ? <><Values title="Pendapatan Bersih" rows={value.laba_rugi.pendapatan} total={value.laba_rugi.pendapatan_bersih} /><Values title="HPP Vendor, Bahan & Stok Ready" rows={value.laba_rugi.beban.filter(row => row.kelompok.startsWith("hpp_"))} total={value.laba_rugi.hpp} /><Values title="Beban Operasional" rows={value.laba_rugi.beban.filter(row => !row.kelompok.startsWith("hpp_"))} total={value.laba_rugi.beban_operasional} /><Panel title="Laba Bersih / SHU"><p className="text-xl font-semibold">{money(value.laba_rugi.shu)}</p></Panel></> : tab === "neraca" ? <><Values title="Aset Lancar" rows={value.neraca.aset.filter(row => ["kas", "piutang_pengiriman", "piutang_escrow", "persediaan"].includes(row.kelompok))} /><Values title="Aset Lain" rows={value.neraca.aset.filter(row => !["kas", "piutang_pengiriman", "piutang_escrow", "persediaan"].includes(row.kelompok))} /><Panel title="Total Aset">{money(value.neraca.total_aset)}</Panel><Values title="Kewajiban / Utang Vendor" rows={value.neraca.kewajiban} total={value.neraca.total_kewajiban} /><Values title="Ekuitas: Modal & SHU" rows={value.neraca.ekuitas} total={value.neraca.total_ekuitas} /><Panel title="Pemeriksaan Neraca"><p>Aset = Kewajiban + Ekuitas</p><p>Selisih: {money(value.neraca.selisih)}</p></Panel></> : <><Panel title="Arus Kas"><Table headers={["Kelompok", "Masuk", "Keluar", "Neto"]}>{Object.entries(value.arus_kas.kelompok).map(([kind, row]) => <tr key={kind} className="border-b"><td className="px-3 py-2">{kind === "mutasi" ? "Mutasi internal antar akun" : kind}</td><td>{money(row.masuk)}</td><td>{money(row.keluar)}</td><td>{money(row.neto)}</td></tr>)}</Table><p className="mt-3 text-sm">Mutasi pokok antar akun bersaldo neto nol; biaya bank masuk arus operasional.</p></Panel><Panel title="Rekonsiliasi Kas"><p>Saldo awal: {money(value.arus_kas.saldo_awal)}</p><p>Saldo akhir: {money(value.arus_kas.saldo_akhir)}</p></Panel></>}</div>}
  </>;
}
