import { useState } from "react";
import { keu, money, today, useChoices, useKeuAction, useResource } from "../api";
import type { Account, Coa, Journal, Page } from "../types";
import { useQuery } from "@tanstack/react-query";
import { BookNotice, useBook } from "./BookSettings";
import UnpostEntry from "./UnpostEntry";
import { InputDialog, useCloseFinanceDialog } from "./FinanceUI";
import { Button, Empty, ErrorMessage, Field, inputClass, Loading, Pager, Panel, Table } from "./UI";

const amountPattern = "[0-9]+(\\.[0-9]{1,2})?";
export default function LedgerFinance() {
  const [transferOpen, setTransferOpen] = useState(false);
  const book = useBook();
  const accounts = useChoices<Account>("/akun");
  const chart = useChoices<Coa>("/coa");
  const [offset, setOffset] = useState(0), [history, setHistory] = useState(false);
  const journals = useResource<Journal>("/jurnal", offset, "", history ? "batal" : "pengerjaan");
  const action = useKeuAction();
  const [reference, setReference] = useState(() => crypto.randomUUID());
  const [source, setSource] = useState(""), [target, setTarget] = useState("");
  if (!book.data?.aktif) return <BookNotice />;
  return <><InputDialog open={transferOpen} onOpenChange={setTransferOpen} title="Transfer antar kas" label="Transfer / isi kembali kas"><Panel title="Transfer / Mutasi Kas"><ErrorMessage error={action.error ?? accounts.error} /><form className="grid gap-3 sm:grid-cols-2" onSubmit={event => { event.preventDefault(); if (!source || source === target) return; const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); void action.mutateAsync({ path: "/mutasi", body: { ...values, referensi: reference } }).then(() => { setReference(crypto.randomUUID()); form.reset(); setSource(""); setTarget(""); setTransferOpen(false); }).catch(() => {}); }}>
    <Field label="Tanggal mutasi"><input required type="date" name="tanggal" defaultValue={today()} className={inputClass} /></Field><Field label="Nominal transfer"><input name="nominal" required inputMode="decimal" pattern={amountPattern} className={inputClass} /></Field>
    <Field label="Akun Kas Asal (Kredit)"><select required name="akun_asal_id" value={source} onChange={event => setSource(event.target.value)} className={inputClass}><option value="">Pilih akun asal</option>{accounts.data?.filter(a => a.aktif).map(a => <option key={a.id} value={a.id}>{a.nama}</option>)}</select></Field><Field label="Akun Kas Tujuan (Debet)"><select required name="akun_tujuan_id" value={target} onChange={event => setTarget(event.target.value)} className={inputClass}><option value="">Pilih akun tujuan</option>{accounts.data?.filter(a => a.aktif && a.id !== source).map(a => <option key={a.id} value={a.id}>{a.nama}</option>)}</select></Field>
    <Field label="Biaya admin bank"><input name="biaya_admin" inputMode="decimal" pattern={amountPattern} defaultValue="0" required className={inputClass} /></Field><Field label="Catatan mutasi"><input name="keterangan" maxLength={2000} className={inputClass} /></Field><Button type="submit" disabled={action.isPending || !source || !target || source === target}>Posting Mutasi Kas</Button>
  </form></Panel></InputDialog><Cashbook accounts={accounts.data ?? []} /><InputDialog title="Penyesuaian pembukuan" label="Penyesuaian / modal"><ManualJournal /></InputDialog>
  <Panel title="Jurnal Buku Besar"><div className="mb-3 flex flex-wrap gap-2"><Button aria-pressed={!history} onClick={() => { setHistory(false); setOffset(0); }}>Jurnal Aktif</Button><Button aria-pressed={history} onClick={() => { setHistory(true); setOffset(0); }}>Jurnal Dibatalkan</Button></div><ErrorMessage error={journals.error} />{journals.isLoading ? <Loading /> : !journals.data?.rows.length ? <Empty /> : <Table headers={["Tanggal", "Jenis", "Keterangan", "Status / Aksi"]}>{journals.data.rows.map(j => <tr key={j.id} className="border-b"><td className="px-3 py-2">{j.tanggal}</td><td>{j.jenis.replaceAll("_", " ")}</td><td>{j.keterangan}<details><summary>Rincian debet / kredit</summary><ul>{j.baris.map(row => <li key={row.id}>{chart.data?.find(a => a.id === row.coa_id)?.nama ?? row.coa_id} · Debet {money(row.debet)} · Kredit {money(row.kredit)}</li>)}</ul></details></td><td>{j.status === "terkirim" && j.jenis !== "pembukaan" ? <UnpostEntry id={j.id} resource="jurnal" /> : <div>{j.status}<p>{j.alasan_batal}</p></div>}</td></tr>)}</Table>}<Pager offset={offset} total={journals.data?.total ?? 0} onChange={setOffset} /></Panel></>;
}
export function Cashbook({ accounts }: { accounts: Account[] }) {
  const [start, setStart] = useState(today().slice(0,7)+"-01"), [end, setEnd] = useState(today()), [account, setAccount] = useState(""), [offset, setOffset] = useState(0);
  const valid = !!start && !!end && start <= end;
  const data = useQuery({ queryKey: ["keu", "buku-kas", start, end, account, offset], queryFn: () => keu<Page<{ id: string; nama: string; tanggal: string; keterangan: string; debet: string; kredit: string; saldo: string }>>(`/buku-kas?tanggal_awal=${start}&tanggal_akhir=${end}&akun_id=${encodeURIComponent(account)}&limit=50&offset=${offset}`), enabled: valid });
  return <Panel title="Buku Kas per Akun"><div className="mb-3 grid gap-3 sm:grid-cols-3"><Field label="Awal buku kas"><input type="date" value={start} onChange={event => { setStart(event.target.value); setOffset(0); }} className={inputClass} /></Field><Field label="Akhir buku kas"><input type="date" value={end} onChange={event => { setEnd(event.target.value); setOffset(0); }} className={inputClass} /></Field><Field label="Filter akun kas"><select value={account} onChange={event => { setAccount(event.target.value); setOffset(0); }} className={inputClass}><option value="">Seluruh akun</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.nama}</option>)}</select></Field></div>{!valid && <p role="alert">Rentang tanggal buku kas tidak valid.</p>}<ErrorMessage error={data.error} />{valid && data.data && <Table headers={["Tanggal", "Akun", "Keterangan", "Debet / Masuk", "Kredit / Keluar", "Saldo Akun"]}>{data.data.rows.map(row => <tr key={row.id} className="border-b"><td className="px-3 py-2">{row.tanggal}</td><td>{row.nama}</td><td>{row.keterangan}</td><td>{money(row.debet)}</td><td>{money(row.kredit)}</td><td>{money(row.saldo)}</td></tr>)}</Table>}<Pager offset={offset} total={data.data?.total ?? 0} onChange={setOffset} /></Panel>;
}
function ManualJournal() {
  const close = useCloseFinanceDialog();
  const accounts = useChoices<Coa>("/coa");
  const action = useKeuAction();
  const [reference, setReference] = useState(() => crypto.randomUUID());
  const [rows, setRows] = useState([{ key: crypto.randomUUID(), coa_id: "", debet: "0", kredit: "0", arus: "operasional" }, { key: crypto.randomUUID(), coa_id: "", debet: "0", kredit: "0", arus: "operasional" }]);
  return <Panel title="Jurnal Manual / Koreksi / Modal"><ErrorMessage error={accounts.error ?? action.error} /><form className="grid gap-3" onSubmit={event => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form)); void action.mutateAsync({ path: "/jurnal", body: { ...values, referensi: reference, baris: rows.map(row => ({ coa_id: row.coa_id, debet: row.debet, kredit: row.kredit, arus: accounts.data?.find(a => a.id === row.coa_id)?.kas_akun_id ? row.arus : null })) } }).then(() => { setReference(crypto.randomUUID()); form.reset(); close(); setRows(rows.map(row => ({ ...row, coa_id: "", debet: "0", kredit: "0" }))); }).catch(() => {}); }}>
    <Field label="Tanggal jurnal manual"><input type="date" name="tanggal" required defaultValue={today()} className={inputClass} /></Field><Field label="Keterangan jurnal manual"><input name="keterangan" required minLength={3} maxLength={2000} className={inputClass} /></Field>
    {rows.map((row, index) => <div key={row.key} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-4"><Field label={`Akun jurnal ${index+1}`}><select required value={row.coa_id} onChange={event => setRows(rows.map(r => r.key === row.key ? { ...r, coa_id: event.target.value } : r))} className={inputClass}><option value="">Pilih akun</option>{accounts.data?.filter(a => a.aktif && !["persediaan","piutang_pengiriman","piutang_escrow","hpp_stok","hpp_vendor","utang_vendor"].includes(a.kelompok)).map(a => <option key={a.id} value={a.id}>{a.nama}</option>)}</select></Field><Field label={`Debet baris ${index+1}`}><input required value={row.debet} inputMode="decimal" pattern={amountPattern} onChange={event => setRows(rows.map(r => r.key === row.key ? { ...r, debet: event.target.value } : r))} className={inputClass} /></Field><Field label={`Kredit baris ${index+1}`}><input required value={row.kredit} inputMode="decimal" pattern={amountPattern} onChange={event => setRows(rows.map(r => r.key === row.key ? { ...r, kredit: event.target.value } : r))} className={inputClass} /></Field>{accounts.data?.find(a => a.id === row.coa_id)?.kas_akun_id && <Field label={`Arus kas baris ${index+1}`}><select value={row.arus} onChange={event => setRows(rows.map(r => r.key === row.key ? { ...r, arus: event.target.value } : r))} className={inputClass}>{["operasional","investasi","pendanaan"].map(a => <option key={a}>{a}</option>)}</select></Field>}{rows.length > 2 && <Button onClick={() => setRows(rows.filter(r => r.key !== row.key))}>Hapus baris {index+1}</Button>}</div>)}
    <div className="flex flex-wrap gap-2"><Button disabled={rows.length >= 100} onClick={() => setRows([...rows,{ key: crypto.randomUUID(),coa_id:"",debet:"0",kredit:"0",arus:"operasional" }])}>+ Tambah Baris Jurnal</Button><Button type="submit" disabled={action.isPending}>Posting Jurnal Seimbang</Button></div><p className="text-sm">Total debet harus sama dengan kredit. Piutang, stok, dan HPP memakai modul khusus. Koreksi jurnal tidak mengubah nominal lama.</p>
  </form></Panel>;
}
